"""Service interface Protocols. Services use these to type-hint without importing."""
from typing import Protocol


class AuthServiceInterface(Protocol):
    def login(self, email: str, password: str) -> "AuthResult": ...
    def get_user(self, user_id: str) -> "User": ...
    def verify_password(self, user_id: str, password: str) -> bool: ...
    def register(self, email: str, password: str) -> "AuthResult": ...
    def add_imap_account(self, user_id: str, account: "ImapAccount", user_password: str) -> "ImapAccountResponse": ...
    def list_imap_accounts(self, user_id: str) -> list["ImapAccountResponse"]: ...
    def delete_imap_account(self, user_id: str, account_id: int) -> bool: ...
    def delete_user(self, user_id: str) -> bool: ...


class MailServiceInterface(Protocol):
    def fetch(self, count: int, unread_only: bool, account: str) -> "MailListResult": ...
    def move(self, indices: list[int], folder: str) -> str: ...
    def read(self, index: int) -> "EmailDetail": ...
    def handle(self, prompt: str, interactive: bool) -> list[dict]: ...
    def to_dict(self) -> dict: ...


class MemoryServiceInterface(Protocol):
    def remember(self, fact: str, user_id: str) -> str: ...
    def recall(self, query: str, user_id: str, top_k: int) -> list[dict]: ...
    def list_memories(self, user_id: str) -> list[dict]: ...
    def forget(self, memory_id: str, user_id: str) -> bool: ...


class SearchServiceInterface(Protocol):
    def search(self, query: str) -> dict: ...
    def browse(self, url: str) -> dict: ...


class LLMServiceInterface(Protocol):
    def complete(self, messages: list[dict], schema: dict, model: str) -> str: ...
    def embeddings(self, text: str, model: str) -> list[float]: ...


class WhisperServiceInterface(Protocol):
    async def transcribe(
        self,
        audio_bytes: bytes,
        *,
        filename: str | None = None,
        language: str | None = None,
        prompt: str | None = None,
    ) -> dict: ...
